---
  application:
    title: "Aitia"
    meta_title: "Aitia"
    meta_description: "Meteor Kitchen - example application"
    theme: "bootswatch-paper"
    roles:
      - "guest"
      - "admin"
      - "user"
      - "associate"
    default_role: "guest"
    send_verification_email: true
    footer_text: "@ Aitia 2015"
    login_with_password: true
    login_with_facebook: true
    collections:
      -
        name: "associates"
        roles_allowed_to_read:
          - "admin"
          - "associate"
          - "user"
        roles_allowed_to_insert: "associate"
        roles_allowed_to_update:
          - "admin"
          - "associate"
        fields:
          -
            name: name
            title: Nombre
            required: true
            exportable: true
          -
            name: last_name
            title: Apellido
            required: true
            exportable: true
          -
            name: "phone"
            title: "Teléfono"
            default: "-"
            required: true
            exportable: true
          -
            name: "email"
            title: "E-mail"
            type: "email"
            required: true
            exportable: true
          -
            name: "sex"
            title: "Sexo"
            input: select
            type: "string"
            input_items: ["Hombre", "Mujer"]
            exportable: true
          -
            name: "dob"
            title: "Fecha de Nacimiento"
            input: "datepicker"
          -
            name: "phoneType"
            title: "Tipo de teléfono"
            input: select
            type: telephone
            input_items: ["android", "iphone", "sin smartphone", "otro"]
          -
            name: "street"
            title: "Calle"
            input: "text"
          -
            name: "city"
            title: "Ciudad"
            input: "text"
          -
            name: "state"
            title: "Estado"
            input: "text"
          -
            name: "postcode"
            title: "Código Postal"
            type: "integer"
          -
            name: "accept_terms"
            title: "¿Estas de acuerdo en asistir a una cita para una orientación?"
            input: checkbox
            display_helper: booleanToYesNo
            type: bool
            required: true
            exportable: true
          -
            name: "why_join"
            title: "Porque estas interesado en formar parte"
            input: textarea
            type: string

    public_zone:
      pages:
        -
          name: "home_public"
          components:
            -
              name: "ask_for_help"
              title: "¿Quieres trabajar?"
              type: "jumbotron"
              text: "Trabajo para todos"
              button_title: "Solicita Acceso"
              button_route: "register_associate"
            -
              name: "how_it_works"
              type: "div"
              title: "Como funciona"
              class: "row"
              components:
                -
                  name: "example_column_1"
                  type: "jumbotron"
                  class: "col-md-4"
                  text: "Busca lo que necesitas"
                  components: []
                -
                  name: "example_column_2"
                  type: "jumbotron"
                  class: "col-md-4"
                  text: "Elige un ayudante"
                  components: []
                -
                  name: "example_column_3"
                  type: "jumbotron"
                  class: "col-md-4"
                  text: "Relájate"
                  components: []
        -
          name: "register_as"
          components:
            -
              name: "home_jumbotron2"
              class: "col-md-6"
              title: "Quiero trabajar"
              type: "jumbotron"
              text: "Trabajo para todos"
              button_title: "Asociarme"
              button_route: "register_associate"
            -
              name: "home_jumbotron"
              class: "col-md-6"
              title: "Necesito Apoyo"
              type: "jumbotron"
              text: "Si necesitas que te ayuden con algo"
              button_title: "Solicitar"
              button_route: "register_user"
        -
          name: "register_associate"
          components:
            -
              name: "ask_for_help"
              title: Registro de Asociado
              type: "form"
              mode: "insert"
              query:
                name: "associate"
                collection: "associates"
                filter: {}
              submit_route: "thanks_associate"
              cancel_route: "home_public"
        -
          name: thanks_associate
          title: Gracias por Registrarte
          type: jumbotron
          text: Nosotros nos pondremos en contacto contigo para agendar nuestra orientación
        -
          name: "login"
          template: "login"
        -
          name: "register"
          template: "register"
        -
          name: "verify_email"
          template: "verify_email"
          route_params:
            - "verifyEmailToken"
        -
          name: "forgot_password"
          template: "forgot_password"
        -
          name: "reset_password"
          template: "reset_password"
          route_params:
            - "resetPasswordToken"
        -
          name: "contact"
          title: "Aitia Contact"
          components:
            -
              name: "div_lorem"
              type: "div"
              class: "row"
              components:
                -
                  name: "div_lorem1"
                  type: "div"
                  class: "col-md-4"
                  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium molestias et laboriosam atque, reprehenderit ipsa, laborum accusamus consectetur ut quo, totam recusandae, animi temporibus dolor repudiandae iste tempore in corrupti?"
                -
                  name: "div_lorem2"
                  type: "div"
                  class: "col-md-4"
                  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium molestias et laboriosam atque, reprehenderit ipsa, laborum accusamus consectetur ut quo, totam recusandae, animi temporibus dolor repudiandae iste tempore in corrupti?"
                -
                  name: "div_lorem3"
                  type: "div"
                  class: "col-md-4"
                  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium molestias et laboriosam atque, reprehenderit ipsa, laborum accusamus consectetur ut quo, totam recusandae, animi temporibus dolor repudiandae iste tempore in corrupti?"
      menus:
        -
          name: "left_menu"
          class: "nav navbar-nav"
          dest_selector: "#menu"
          items:
            -
              title: "Como funciona"
              route: "home_public"
        -
          name: "right_menu"
          class: "nav navbar-nav navbar-right"
          dest_selector: "#menu"
          items:
            -
              title: "Suscríbete"
              route: "register"
            -
              title: "Login"
              route: "login"
    private_zone:
      pages:
        -
          name: "home_private"
          title: "Welcome {{userFullName}}!"
        -
          name: "admin"
          roles:
            - "admin"
          pages:
            -
              name: "users"
              components:
                -
                  name: "view"
                  type: "data_view"
                  title: "Users"
                  text_if_empty: "No users yet"
                  query:
                    name: "admin_users"
                    collection: "users"
                    filter: {}
                  fields:
                    -
                      name: "profile.name"
                      title: "Name"
                    -
                      name: "profile.email"
                      title: "E-mail"
                    -
                      name: "roles"
                      title: "Role"
                  insert_route: "admin.users.insert"
                  edit_route: "admin.users.edit"
                  edit_route_params:
                    -
                      name: "userId"
                      value: "this._id"
                  details_route: "admin.users.details"
                  details_route_params:
                    -
                      name: "userId"
                      value: "this._id"
              pages:
                -
                  name: "details"
                  route_params:
                    - "userId"
                  components:
                    -
                      name: "details_form"
                      type: "form"
                      mode: "read_only"
                      title: "User details"
                      query:
                        name: "admin_user"
                        collection: "users"
                        filter:
                          _id: ":userId"
                      fields:
                        -
                          name: "profile.name"
                          title: "Name"
                        -
                          name: "profile.email"
                          title: "E-mail"
                          type: "email"
                        -
                          name: "roles"
                          title: "Role"
                      close_route: "admin.users"
                      back_route: "admin.users"
                -
                  name: "insert"
                  components:
                    -
                      name: "insert_form"
                      type: "form"
                      mode: "insert"
                      title: "Add new user"
                      submit_route: "admin.users"
                      cancel_route: "admin.users"
                      query:
                        name: "users_null"
                        collection: "users"
                        filter:
                          _id: null
                      fields:
                        -
                          name: "profile.name"
                          title: "Name"
                          required: true
                        -
                          name: "profile.email"
                          title: "E-mail"
                          type: "email"
                          required: true
                        -
                          name: "password"
                          title: "Password"
                          input: "password"
                          required: true
                -
                  name: "edit"
                  route_params:
                    - "userId"
                  components:
                    -
                      name: "edit_form"
                      type: "form"
                      mode: "update"
                      title: "Edit user"
                      submit_route: "admin.users"
                      cancel_route: "admin.users"
                      query:
                        name: "admin_user"
                        collection: "users"
                        filter:
                          _id: ":userId"
                      fields:
                        -
                          name: "profile.name"
                          title: "Name"
                          required: true
                        -
                          name: "profile.email"
                          title: "E-mail"
                          type: "email"
                          required: true
                        -
                          name: "roles"
                          type: "array"
                          title: "Role"
                          input: "radio"
                          input_items:
                            -
                              value: "user"
                              title: "User"
                            -
                              value: "admin"
                              title: "Admin"
                            -
                              value: "blocked"
                              title: "Blocked"
          menus:
            -
              name: "side_menu"
              class: "nav nav-stacked nav-pills"
              items:
                -
                  title: "Users"
                  route: "admin.users"
        -
          name: "user_settings"
          roles:
            - "user"
            - "admin"
          pages:
            -
              name: "profile"
              components:
                -
                  name: "edit_form"
                  type: "form"
                  mode: "update"
                  title: "Edit your profile"
                  submit_route: "user_settings.profile"
                  query:
                    name: "current_user_data"
                    collection: "users"
                    filter:
                      _id: "Meteor.userId()"
                    find_one: true
                  fields:
                    -
                      name: "profile.name"
                      title: "Name"
                      required: true
                    -
                      name: "profile.email"
                      title: "E-mail"
                      type: "email"
                      required: true
                    -
                      name: "profile.facebook"
                      title: "Facebook URL"
                    -
                      name: "profile.google"
                      title: "Google+ URL"
                    -
                      name: "profile.twitter"
                      title: "Twitter ID"
                    -
                      name: "profile.website"
                      title: "Website URL"
            -
              name: "change_pass"
              template: "change_pass"
          menus:
            -
              name: "side_menu"
              class: "nav nav-stacked nav-pills"
              items:
                -
                  title: "Profile"
                  route: "user_settings.profile"
                -
                  title: "Change password"
                  route: "user_settings.change_pass"
        -
          name: "logout"
          template: "logout"
      menus:
        -
          name: "left_menu"
          class: "nav navbar-nav"
          dest_selector: "#menu"
          items:
            -
              title: "Home"
              route: "home_private"
        -
          name: "right_menu"
          class: "nav navbar-nav navbar-right"
          dest_selector: "#menu"
          items:
            -
              title: "Admin"
              route: "admin"
            -
              title: "{{userEmail}}"
              items:
                -
                  title: "Settings"
                  route: "user_settings"
                -
                  title: "Logout"
                  route: "logout"
